### ISSUE TITLE
tickets pos in web portal 

### ISSUE THREAD

**Issue by Patrickkappert** [coopiteasy/vertical-cooperative#147]
In the website portal there is a view of the total amount of purchases but not all the tickets generated for the client at the point of sale.

**Comment by robinkeunen** [comment]
Indeed, please submit a PR, we will review and maybe integrate it :-)

**Comment by Patrickkappert** [comment]
I found this: https://apps.odoo.com/apps/modules/12.0/pos_website/

for 25 euros.

**Comment by robinkeunen** [comment]
Nice, feel free to install it on your side :-)
