### ISSUE TITLE
Why is allowed to create Cooperators whit 0 as Cooperator Number?

### ISSUE THREAD

**Issue by eugenichafer** [coopiteasy/vertical-cooperative#154]
A problem that we have repeatedly encountered with costumers is that new cooperators can be created from the view "EMC->Contacts->Cooperators".  These cooperators have "0" as a cooperator number. We don't understand why this is possible. Maybe it was usefull to hide "Create" button in this view

https://user-images.githubusercontent.com/64070973/113742044-814d7d00-9702-11eb-8194-1cc18cce72ed.mov

**Comment by enricostano** [comment]
@houssine78 @robinkeunen would you mind to review this issue?

**Comment by houssine78** [comment]
@enricostano @eugenichafer in fact a cooperator is not created directly from the form view. We always have to follow the standard subscription flow. As the cooperator number is a integer the default value 0 is given by Odoo in standard for all the integer field AFAIK.

In addition, the cooperator number is not displayed as far as the effective cooperator field is not True (checkbox ticked).

it's the standard res.partner view so we can't hide the create button to do that we should create a dedicated form view. But it's maybe possible to add an option "no_create" in the context field of the act_windows for the cooperator menu (and also for the one of the cooperator candidate).

If you propose such PR we'll could accept it as this is not the way cooperators have to be registered.

**Comment by enricostano** [comment]
Thanks @houssine78 !

I understand the technical aspect, the main issue is that users are creating "members" by mistake and we're getting a good number of support tickets related to this.

We'll investigate your "no_create" suggestion and see if we can propose a PR. Bye!

**Comment by enricostano** [comment]
@houssine78 is it possible that your PR https://github.com/coopiteasy/vertical-cooperative/pull/158 would help to solve this issue?

**Comment by houssine78** [comment]
@enricostano no it won't. This is just to display the field cooperator for non admin and in read only

**Comment by enricostano** [comment]
@houssine78 @robinkeunen what about setting `member` and `coop_candidate` fields as `readonly` in the form view?
