### ISSUE TITLE
RFC Moving Easy My Coop to OCA

### ISSUE THREAD

**Issue by robinkeunen** [coopiteasy/vertical-cooperative#170]
Easy My Coop, also developped originally for the BEES coop but is now used by 25+ cooperatives. Additionnaly other IT cooperatives (coopdevs, cooperatic) are starting to use and contribute to the solution for their own customers.

At Coop IT Easy, we believe it's time to go further than just applying the AGPL license and to *really* make this project Open Source. By that we mean

- bring together a community around the code,
- make the code easier to contribute to
- **moving under the OCA umbrella**

## Why do it ?

- Raise the code quality to the OCA standards.
- Release the project ownership ;
- Become the reference repository for *Share Management* with Odoo ;
- Make contributions easier for people outside Coop IT Easy ;
- Grow the project visibility and attract new customers and contributors ;
- Give a better understanding of the roadmap ;

### Required

1. Rename repositories and modules to more generic names
	- cf https://github.com/beescoop/Obeesdoo/issues/248 
2. Remove all references to Obeesdoo and Easy My Coop
	- in python code
	- and xml data
	- cf https://github.com/beescoop/Obeesdoo/issues/249 (archived)
3. Add demo data to demonstrate basic flows
	- cf https://github.com/beescoop/Obeesdoo/issues/250 (archived)
4. Cover main flows with unit tests
	- cf https://github.com/beescoop/Obeesdoo/issues/250 (archived)
5. Rename models

## How

The migration will be done **incrementally** in the order given in the previous section. Each improvement will bring its migration script relying on the *OCA Open Upgrade* Library.

Following the [OCA Repository Policy](https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/oca_repository_policy.rst), the repositories and module will be proposed as a topic repository for Easy My Coop - Share Management

The repositories will be marked as [Incubation Repositories](https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/oca_repository_policy.rst#incubation-repositories). The modules should be marked with the [beta maturity levels](https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/oca_module_lifecycle_development_status.rst) because, even though they're used in production, they will be heavily refactored.

As we split and improve the modules, some might be extracted to the relevant main OCA repositories (Sale, POS, ...).

> In the long run, they should contain only the specific features needed. Features also relevant for other use cases, outside the vertical’s perimeter, should ideally be extracted and moved to the appropriate Main or Topic repository.

![vertical-cooperative-repo-refactor-1 0 0](https://user-images.githubusercontent.com/17589077/149750369-34ea7875-4afa-41dc-afa9-cb66113ba6bc.png)

## Financing

Coop IT Easy received a subsidy from the Bruxelles Region to *foster intercooperation around the digital commons*. This subsidy will cover three endeavours:

1. Bring together a community of users (cooperative supermarkets) to co-finance their ERP solution ;
2. Build a community of developpers to collaborate on shared code ;
3. Make the Easy My Coop and Obeesdoo modules easier to collaborate to.

This RFC describes the work needed in the 3rd item. The subsidy will cover the costs of 80 days of development and tests by Coop IT Easy.

The subsidy runs from July 2021 to December 2022

## Resources

[OCA Repository Policy](https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/oca_repository_policy.rst)

[PYSI project summary](https://docs.google.com/document/d/16ADIMfqTwOezt-EQyYDDK9iMUyQpf0gQD6gPixjqdxw/edit#heading=h.idlvbaiklpk0) (french)

cf https://github.com/beescoop/Obeesdoo/issues/247

**Comment by robinkeunen** [comment]
![emc_dependencies](https://user-images.githubusercontent.com/3082119/150379092-b08d1eb6-deb2-470f-90bf-1ef64c30f40c.png)

**Comment by polchampion** [comment]
### Listing vertical-cooperative modules to be reorganised, by depth wrt `easy_my_coop`

**Depth 1**
- [x] `easy_my_coop`
- [ ] `partner_age`
- [ ] `website_recaptcha_reloaded`

**Depth 2**
- [ ] `easy_my_coop_be`
- [ ] `easy_my_coop_fr`
- [ ] `easy_my_coop_ch`
- [ ] `easy_my_coop_es`
- [ ] `easy_my_coop_es_website`
- [ ] `easy_my_coop_api`
- [ ] `easy_my_coop_api_logs`
- [ ] `easy_my_coop_website`
- [ ] `easy_my_coop_website_portal`
- [ ] `easy_my_coop_taxshelter_report`
- [ ] `easy_my_coop_loan`
- [ ] `easy_my_coop_dividend`
- [ ] `easy_my_coop_export_xlsx`
- [ ] `beesdoo_easy_my_coop`

**Depth 3**
- [ ] `easy_my_coop_connector`
- [ ] `easy_my_coop_website_taxshelter`
- [ ] `easy_my_coop_loan_website`
- [ ] `easy_my_coop_loan_account`
- [ ] `easy_my_coop_loan_bba`

**Depth 4**
- [ ] `easy_my_coop_loan_account_be`
