### ISSUE TITLE
RFC Remake the subscription request website form

### ISSUE THREAD

**Issue by victor-champonnois** [coopiteasy/vertical-cooperative#181]
We propose to remake the subscription request website form from scratch.

# Why do it ?

The actual form template has several issues:
- code redundancy between company and non-company form
- use of HTML table for "Part number" field
- display issues for small screens (mobile)

# What do we need to do ?

Redo the templates from scratch:
- use HTML5 input + custom JS for the part number field
- use template inheritance to remove redundancies
- get rid of HTML tables and use Bootstrap columns
- center the form

@enricostano  @danypr92 @StCyr

**Comment by enricostano** [comment]
WOW, nice! :clap: 

cc/ @daniquilez
