### ISSUE TITLE
Rename `easy_my_coop` to `cooperator`

### ISSUE THREAD

**Issue by polchampion** [coopiteasy/vertical-cooperative#203]
- [x] rename `easy_my_coop` to `cooperator`
- [x] merge  with property_cooperator_account functionality from `easy_my_coop_es`
- [x] repercussions 

related PR : 
- https://github.com/coopiteasy/vertical-cooperative/pull/202
- https://github.com/beescoop/Obeesdoo/pull/312
- https://github.com/coopiteasy/investor-wallet-platform/pull/74

**Comment by polchampion** [comment]
@robinkeunen A tester ou pas encore ? Si oui, où ? J'imagine qu'il faut tester tout le flux EMC. Je n'ai pas compris ce qu'était cette fonctionnalitéproperty_cooperator_account, par contre.

**Comment by robinkeunen** [comment]
@polchampion A tester mais plutot sur la PR liée (cf colonne de droite). Pour tester : suivre un flux classique de prise de part. Pas besoin d'aller dans le détail pour le moment.

La "fonctionnalité property_cooperator_account" déplace une contrainte sur le compte du journal de souscription d'un module à celui-ci. Le but de cette contraindre est de restreindre les comptes assignables au journal à ceux qui ne sont pas dépréciés (`deprecated`).

**Comment by polchampion** [comment]
@robinkeunen Tested share subscription flow for BE, FR and CH. Feedback in [this document](https://docs.google.com/spreadsheets/d/11mkW2B-j0T1avBgMMcGClrWtRO5OUlbUUv5XoMdd1fY/edit#gid=0)
