### ISSUE TITLE
Rename `easy_my_coop_be` to `l10n_be_cooperator`

### ISSUE THREAD

**Issue by polchampion** [coopiteasy/vertical-cooperative#207]
- [x]  Rename `easy_my_coop_be` to `cooperator_be`

Estimated time - 8h

Module contains these functionalities :
- Belgian legal form on partner
- Default values for communications on invoice

**Comment by victor-champonnois** [comment]
@polchampion c'est en test sur https://oufticoop.test.coopiteasy.be/

**Comment by polchampion** [comment]
@coccinouille Testé et approuvé
