### ISSUE TITLE
Rename `easy_my_coop_fr` to `l10n_fr_cooperator`

### ISSUE THREAD

**Issue by polchampion** [coopiteasy/vertical-cooperative#208]
- [ ]  Rename `easy_my_coop_fr` to `cooperator_fr`

Estimated time - 8h

Module contains these functionalities :
- French legal form on partner
- Remove IBAN field from required subscription request fields

**Comment by victor-champonnois** [comment]
@polchampion en test sur demain.komunigi.test.coopiteasy.be/
