### ISSUE TITLE
Split and rename `easy_my_coop_es` to `l10n_es_cooperator`

### ISSUE THREAD

**Issue by polchampion** [coopiteasy/vertical-cooperative#210]
- [x]  Move the following `easy_my_coop_es` functionality to `cooperator` (Change property_cooperator_account to not accept deprecated account)
- [x] Rename `easy_my_coop_es` to `cooperator_es` 
- [x] https://github.com/coopiteasy/vertical-cooperative/issues/211

Estimated time - 8h

Module contains these functionalities :
- Change property_cooperator_account to not accept deprecated account
- Add tax identification to subscription request and partner

**Comment by robinkeunen** [comment]
Leaving this one to coopdevs @enricostano
