### ISSUE TITLE
Merge  `easy_my_coop_es_website` into `l10n_es_cooperator` 

### ISSUE THREAD

**Issue by polchampion** [coopiteasy/vertical-cooperative#211]
- [ ] Merge `easy_my_coop_es_website` with the following `easy_my_coop_es` functionality (Add tax identification to subscription request and partner)
- [ ] Rename the merged `easy_my_coop_es` and `easy_my_coop_es_website` to `cooperator_es` 

Estimated time -  16h

Module contains the following functionality :
- add tax identification to subscription request website form

**Comment by robinkeunen** [comment]
Leaving this one to coopdevs @enricostano
