### ISSUE TITLE
Rename `easy_my_coop_loan` to (`account_loan_issue ` ?)

### ISSUE THREAD

**Issue by polchampion** [coopiteasy/vertical-cooperative#217]
- [ ] Rename `easy_my_coop_loan` to `account_loan_subscription`, `account_loan_issue` (?)
- [ ] merge with `oca/account-financial-tools/account_loan`

Estimated time : 16h

Module contains the following functionalities:
- Loan management

**Comment by victor-champonnois** [comment]
@polchampion @robinkeunen on est sûr du nom pour celui là ? Il ne faut pas quelque chose de plus précis ? Il y a un module OCA qui s'appelle [account_loan](https://apps.odoo.com/apps/modules/12.0/account_loan/)

**Comment by robinkeunen** [comment]
@victor-champonnois The best would be to merge it with the module from the OCA. Let's leave it on the side for now as it is used very little.
