### ISSUE TITLE
`partner_age`

### ISSUE THREAD

**Issue by polchampion** [coopiteasy/vertical-cooperative#219]
- [ ] Remove existing module `partner_age`
- [ ] Replace it with the OCA module `partner_contact_birthdate` : https://github.com/OCA/partner-contact/tree/12.0/partner_contact_birthdate
     - Rename dependencies
     - Check that it works

Module contains the following functionality: 
- Add age computation on partner

**Comment by polchampion** [comment]
@coccinouille Peux-tu détailler les actions ? Je n'ai pas bien compris ce qu'il fallait faire pour ce module.

**Comment by victor-champonnois** [comment]
Todo:
- Supprimer le module existant
- le remplacer par le module OCA https://github.com/OCA/partner-contact/tree/12.0/partner_contact_birthdate
    - renommer les dépendances
    - vérifier le fonctionnement

**Comment by polchampion** [comment]
[EDITED] Je vois que les deux modules sont installés sur oufticoop

**Comment by victor-champonnois** [comment]
@polchampion C'est en test sur oufticoop.test.coopiteasy.be
- C'est normal que les deux modules soient installés. On ne supprime pas le module partner_age car il est encore utilisé ailleurs.
- J'imagine qu'il faut juste tester que le calcul de l'age se fasse bien dans EMC.

**Comment by polchampion** [comment]
>     * C'est normal que les deux modules soient installés. On ne supprime pas le module partner_age car il est encore utilisé ailleurs.
> 
>     * J'imagine qu'il faut juste tester que le calcul de l'age se fasse bien dans EMC.

Il y a un moyen de voir où exactement ce calcul est utilisé dans EMC ? En tous cas si c'est la valeur affichée sur le Contact dans l'onglet Informations personnelles, ça a l'air de marcher exactement pareil.

**Comment by victor-champonnois** [comment]
OK, oui c'est seulement sur le modèle partner, donc je pense que c'est OK.

**Comment by victor-champonnois** [comment]
@robinkeunen There is an issue now since both partner_age and partner_contact_birthdate are installed: both add "Age" to the contact form. So I think we should reconsider removing partner_age (and using partner_contact_birthdate for beesdoo_easy_my_coop). 
The only relevant difference seems to be that partner_age implements a `_search` method on age, while partner_contact_birthdate does not. Maybe we could propose a PR with this feature, rather than using our own module ?
If we decide to do this : this is the new PR  https://github.com/coopiteasy/vertical-cooperative/pull/327

If we decide to keep it, then we should just remove the partner view ? But we would have duplicate code for the "Age" field.

**Comment by robinkeunen** [comment]
@victor-champonnois I think proposing the PR to the OCA and removing `partner_age` is the way to go.

**Comment by victor-champonnois** [comment]
@polchampion Could you test this one ?
To test:
- Age is correctly computed
- No 'age' field duplication
- beesdoo_easy_my_coop requires to be >18 to be a worker, otherwise the partner is recorded as "eater" during the susbcription request -> Check that this behavior applies correctly.

**Comment by polchampion** [comment]
@victor-champonnois L'âge est toujours en double sur `bees` ([la mise à jour du module](https://bees.test.coopiteasy.be/web#id=298&action=36&model=ir.module.module&view_type=form&menu_id=5) n'est pas complète)

**Comment by victor-champonnois** [comment]
@polchampion Sorry, I fixed it, but the test server moves a lot currently. I'll ping you again when it's OK to test.

**Comment by polchampion** [comment]
@victor-champonnois je peux tester encore cette aprèm/max mercredi si tu me dis que c'est ok.

**Comment by victor-champonnois** [comment]
@polchampion C'est OK pour tester cette aprem :+1:

**Comment by robinkeunen** [comment]
@victor-champonnois ok to close this issue?
