### ISSUE TITLE
Rename `website_recaptcha_reloaded` to `portal_recaptcha`

### ISSUE THREAD

**Issue by polchampion** [coopiteasy/vertical-cooperative#221]
- [ ] `website_recaptcha` (formely `website_recaptcha_reloaded`) should be named `portal_recaptcha`
- [ ] leave `portal_recaptcha` in _vertical-cooperative_

**Comment by robinkeunen** [comment]
~~close in favor of https://github.com/coopiteasy/vertical-cooperative/issues/214~~
