### ISSUE TITLE
Write a script to launch the migration script on all databases

### ISSUE THREAD

**Issue by robinkeunen** [coopiteasy/vertical-cooperative#224]
Write a script to launch the migration scrip on all databases
- script is at the root of vertical-cooperative

**Comment by victor-champonnois** [comment]
Does it make sense to update the databases that contains module that has not been migrated yet (e.g. bees ?) Migrating will fail for these DB. So maybe the script should take the name of the DB to update as input ?

**Comment by robinkeunen** [comment]
The command to launch the migration script : 
```
cat src/coopiteasy/vertical-cooperative/rename_deprecated_modules.py | /home/komunigi/venv/bin/odoo shell --config /home/komunigi/odoo.conf --logfile /dev/stdout --stop-after-init -d oufticoop-komunigi-test
```

**Comment by carmenbianca** [comment]
Two scripts.

Super basic bash script:

```bash
#!/bin/bash

# Usage: rename_depreacted_modules.sh database-name-here

cat src/coopiteasy/vertical-cooperative/rename_deprecated_modules.py | /home/komunigi/venv/bin/odoo shell --config /home/komunigi/odoo.conf --logfile /dev/stdout --stop-after-init -d $1
```

Python script with some filtering + creating new databases:

```python
#!/usr/bin/env python3

import datetime
import logging
import subprocess
import sys

_logger = logging.getLogger(__name__)


def all_databases():
    result = subprocess.run(["ociedoo", "list-db"], check=True, stdout=subprocess.PIPE)
    output = result.stdout.decode("utf-8")
    return [line for line in output.splitlines() if line]


def filter_databases(databases):
    return [database for database in databases if database.endswith("-test")]


def now():
    return datetime.datetime.now().strftime("%Y-%m-%dT%H-%m")


def main():
    logging.basicConfig(level=logging.INFO)
    databases = filter_databases(all_databases())
    for database in databases:
        new_database = f"{database}-renamedep-{now()}"
        _logger.info(f"Creating {new_database} from {database}")
        subprocess.run(["ociedoo", "copy-db", database, new_database], check=True)
        subprocess.run(["./rename_deprecated_modules.sh", new_database], check=True)


if __name__ == "__main__":
    main()
```

**!!! CAUTION !!!**

The test server currently has _too little spare storage space_ to perform the above script!

**!!! CAUTION !!!**

How to make this better:

- [x] Better filtering. Some test databases like `brasseriedurenard-komunigi-test-u-all-04-03-2022` are not filtered out.
- [ ] Maybe some flag that toggles whether to create a new DB or not.
- [ ] Catch errors and continue the for-loop if something goes wrong on one DB.
- [ ] Create an easy way of deleting all `renamedep` databases.

**Comment by victor-champonnois** [comment]
From what I understand of your script the reference database is now called like *-komunigi-test and the migrated database is called *komunigi-test-renamedep-<date>. Is it correct ?
If yes, the *u-all-07-03-2022 databases are useless and can be removed now ?

**Comment by carmenbianca** [comment]
@coccinouille The migrated database is called `[...]-komunigi-test-renamedep-yyyy-mm-ddThh-mm`. Whether the `u-all` databases are useless, I don't really know. Maybe?

**Comment by robinkeunen** [comment]
I find them useful to start from a restored database without actually restoring a new backup + update all + install mass_operation_abstract.

**Comment by robinkeunen** [comment]
So I guess these databases should be filtered out as well.

**Comment by carmenbianca** [comment]
@robinkeunen Should we instead filter on `.*-test$`?

**Comment by robinkeunen** [comment]
looks good yes.

**Comment by carmenbianca** [comment]
:thumbsup: Adjusted the script above to do that instead.

**Comment by robinkeunen** [comment]
@victor-champonnois improves (speed) the script for 12-test and prepares a script for 12-prod.

**Comment by victor-champonnois** [comment]
The deployment script (to be tested in 12-test during a non-busy hour)
```
#!/bin/bash

echo "migrating the dbs"
ociedoo stop-odoo
cd /home/odoo12/src/coopiteasy/vertical-cooperative/
./rename_all_deprecated_modules.py
ociedoo start-odoo

echo "updating the db"
source venv/bin/activate
ociedoo update-module all -d all --stop-before-start-after -y ;
```

**Comment by robinkeunen** [comment]
@victor-champonnois closing this as we decided
- to use the script for the deployment next week
- to avoid using a script altogether for obeesdoo modules.
