### ISSUE TITLE
Remove beesdoo_base from beesdoo_shift dependencies

### ISSUE THREAD

**Issue by robinkeunen** [coopiteasy/vertical-cooperative#226]
PR: https://github.com/beescoop/Obeesdoo/pull/314

**Comment by robinkeunen** [comment]
Extract member card module will be done later (focusing on vertical-cooperative)

**Comment by polchampion** [comment]
@robinkeunen `beesdoo_base` est toujours mentionné dans les dépendances de `beesdoo_shift`
Je ne sais pas s'il y a vraiment quelque chose à tester sinon ?

**Comment by robinkeunen** [comment]
Bien vu, je n'ai pas été au bout du déploiement.

**Comment by robinkeunen** [comment]
@polchampion c'est déployé sur pour les supermarchés du serveur de test (càd pas komunigi).
