### ISSUE TITLE
Remove disabled constraint unique_number on res.partner.bank

### ISSUE THREAD

**Issue by carmenbianca** [coopiteasy/vertical-cooperative#241]
OCA won't accept this disabled constraint. We should move it to a custom module or sanitise our clients' databases.

https://gestion.coopiteasy.be/web#id=9262&action=475&active_id=221&model=project.task&view_type=form&menu_id=536

Fixed by https://github.com/coopiteasy/vertical-cooperative/pull/310

Replaced by https://github.com/coopiteasy/addons/pull/226

- [x] deploy in test
- [x] notify Pol
- [ ] merge 
- [ ] and port to 14.0

**Comment by robinkeunen** [comment]
@carmenbianca I saw you worked on this, can you link the PR here and update the task status ?

**Comment by robinkeunen** [comment]
@carmenbianca up

**Comment by carmenbianca** [comment]
@robinkeunen added links to PRs

I don't think there's an Odoo task related to this. It's just Komunigi.

**Comment by carmenbianca** [comment]
not sure why this was closed

**Comment by robinkeunen** [comment]
I thought it would be included in the merge of 12.0-komunigi into 12.0. Can you 

- [ ] ~~deploy in test~~
- [ ] ~~notify Pol~~
- [ ] ~~merge~~
- [ ] ~~and port to 14.0~~

**Comment by carmenbianca** [comment]
Poorly written SQL query that gives you all partners violating the constraint:

```sql
select partner_id, sanitized_acc_number
from res_partner_bank
where sanitized_acc_number in (
    select distinct sanitized_acc_number
    from (
        select sanitized_acc_number, company_id, count(*)
        from res_partner_bank
        group by sanitized_acc_number, company_id
        having count(*) > 1
    ) as sub
) order by sanitized_acc_number;
 ```

**Comment by victor-champonnois** [comment]
Leaving this issue here (not moving it to OCA), since I assume it will be closed soon.
