### ISSUE TITLE
refactor states in easy_my_coop

### ISSUE THREAD

**Issue by robinkeunen** [coopiteasy/vertical-cooperative#286]
Inconsistent state names: 

```py
state = fields.Selection(
    [
        ("draft", "Draft"),
        ("block", "Blocked"),  => blocked
        ("done", "Done"),
        ("waiting", "Waiting"),
        ("transfer", "Transfer"), => transferred ? I do not see any place where this state is assigned.
        ("cancelled", "Cancelled"),
        ("paid", "paid"),
    ],
)
```
Inconsistent function names for state change :
```py
def validate_subscription_request(self): => process request and set to done
def block_subscription_request(self):    => set to block
def unblock_subscription_request(self):  => set to draft
def cancel_subscription_request(self):   => set to cancelled
def put_on_waiting_list(self):           => set to waiting
```
=> use consistent naming, "subscription_request" is useless

+ What is the difference between waiting and blocked ?

+ enforce constraints consistent with the button display

+ maybe use / refactor update_state defined in emc_api

+ check the constraints and visibility of state changes :

+ visibility of validation button: attrs="{'invisible':['|',('state','not in',['draft','waiting']),('validated','=',False)]}"

Also a comment from Hugues on a [connector PR](https://github.com/coopiteasy/vertical-cooperative/pull/195):

instead of hard-coding all possible transitions, i think it would be better to define all of them in one place (in a dict containing sets for example), and define a function that checks whether a transition is possible and raises the corresponding ValidationError if not (constructing a readable string from the values).

this would also allow to have only one method to change the state (.set_state(), for example) instead of one for each state.

moreover, defining all the states as "constants" instead of using strings directly would be better.

**Comment by victor-champonnois** [comment]
closed in favor of https://github.com/OCA/cooperative/issues/28
