### ISSUE TITLE
When taking more shares from the backend for existing cooperator: not taken into account in partner form.

### ISSUE THREAD

**Issue by robinkeunen** [coopiteasy/vertical-cooperative#287]
Lorsqu'on fait une demande de souscription depuis le back end pour un coopérateur existant (augmentation des parts), si on change les infos dans la demande, ce n'est pas changé dans la fiche contact.

A voir si c'est souhaitable?

**Comment by victor-champonnois** [comment]
closed in favor of https://github.com/OCA/cooperative/issues/27
