### ISSUE TITLE
UX: reorganise configurations 

### ISSUE THREAD

**Issue by robinkeunen** [coopiteasy/vertical-cooperative#289]
@enricostano coopdevs had some ideas about this.

**Comment by robinkeunen** [comment]
- move the configurations on the company views to a specific "cooperator" menu in res.config.setting (general parameters).
- add access to this new view from the Cooperator / Configuration menu

**Comment by victor-champonnois** [comment]
closed in favor of https://github.com/OCA/cooperative/issues/26
