### ISSUE TITLE
generate all .pot and po (after renaming modules and xml_ids)

### ISSUE THREAD

**Issue by robinkeunen** [coopiteasy/vertical-cooperative#294]
there's a good number of translation issues in the document. they can be divided into several categories:

1. expected. the source term was changed/newly introduced/never translated.
2. unexpected. the translation value _differs_ from the translation provided by the module. these need to be either manually fixed or force-updated.
3. differently translated between `fr` and `fr_BE`. Is there a reason these translations are separate?

**Comment by victor-champonnois** [comment]
@polchampion suite à la réunion sur les traductions, voici ou on en est là dessus. 

>     1. expected. the source term was changed/newly introduced/never translated.

Il faut les traduire sur la DB blank.komunigi.test.coopiteasy.be. J'y ai chargé les trois langues (fr-fr, fr-be, fr-ch). J'imagine que c'est toi ou moi qui devont s'en charger. 
**-> Done**

>     2. unexpected. the translation value _differs_ from the translation provided by the module. these need to be either manually fixed or force-updated.

De ce qu'on a conclu de la réunion c'est qu'il ne faut pas changer les changements faits par les clients sur leur propre DB. Rien ne sert de les forcer à appeler leur module "Cooperateur" plutôt que Easy My Coop si ça doit écraser des changements qu'ils ont fait eux-même. Par ex. le nid utilise l'écriture inclusive, il ne faut pas écraser leurs traductions.

Par contre les traductions ne marchent pas toujours sur les DB existantes. Par exemple sur demain.komunigi.test le menu Cooperators n'est pas traduit. Il faut décider ce qu'on fait à ce moment là, mais moi je pense qu'il faut laisser tel quel. 

Peut-être que, si on trouve le moyen d'écraser les modification faites par le client on peut leur proposer, soit de conserver leur modifs mais de les laisser gérer les traductions manquantes eux-mêmes, soit d'écraser leur modifs pour appliquer les traductions dans le code. Qu'en penses-tu?
**-> Non, on ne touche pas au traductions des clients**

>     3. differently translated between `fr` and `fr_BE`. Is there a reason these translations are separate?

Il faut le plus possible harmoniser ça. Je pense qu'on peut faire le travail de 1. sur une langue (fr-be par ex.), puis mettre tous les changements dans les autres fichiers po. Il y a peut-être des logiciels qui permettent de faire ça facilement.
**-> DONE**

**Comment by victor-champonnois** [comment]
@polchampion Comme je suis bloqué sur l'avancement de komunigi par ça et que j'ai un peu de temps je vais m'en occuper.
