### ISSUE TITLE
As a cooperator user, I cannot register a payment when prisme_invoice_swiss_qrbill is installed

### ISSUE THREAD

**Issue by robinkeunen** [coopiteasy/vertical-cooperative#296]
"pas ok : erreur quand clic sur le menu Demande de libération de capital ""ValueError: Le champ `qrcode_status` n'existe pas

Contexte de l'erreur :
Vue `account.invoice.form`
[view_id: 507, xml_id: account.invoice_form, model: account.invoice, parent_id: n/a]"""

(cf Le Nid)

**Comment by vdewulf** [comment]
Actually, same issue when clicking on Comptabilité > Factures clients.
I suppose this is an issue related to the module prisme_invoice_swiss_qrbill is installed (or a certain version of this module).
On production DB, no issue.
On test DB (https://lenid.test.coopiteasy.be/), no issue either.
On https://lenid.komunigi.test.coopiteasy.be/ DB, there is an issue.
I don't know if this investigation can help or not.

**Comment by robinkeunen** [comment]
@vdewulf It is now working : no code fix, it was a problem of server configuration.
