### ISSUE TITLE
Refactor `subscription/subscribe_share ` route so that noqa: C901 (method too complex) can be removed

### ISSUE THREAD

**Issue by robinkeunen** [coopiteasy/vertical-cooperative#303]
https://github.com/coopiteasy/vertical-cooperative/blob/b1f887c9c1bf8ecb1ee482c5ceaddf3d03dc6273/easy_my_coop_website/controllers/main.py#L381-L387

**Comment by victor-champonnois** [comment]
closed in favor of https://github.com/OCA/cooperative/issues/24
