### ISSUE TITLE
`cooperator_portal` has `website` as dependency

### ISSUE THREAD

**Issue by carmenbianca** [coopiteasy/vertical-cooperative#311]
@victor-champonnois Do you know why this is?

**Comment by victor-champonnois** [comment]
@carmenbianca 
I haven't work on this module, but in my understanding is the following:
The website dependency is needed in the controller (the routes have a `website=True` option, which provides some website integration). There was a discussion [here](https://github.com/coopiteasy/vertical-cooperative/pull/257) about whether we should keep this dependency for the frontend form, and the result was to keep the website dependency, so I think it is the same for cooperator_portal.
