### ISSUE TITLE
cannot find dependency modul "partner_contact_birthdate"

### ISSUE THREAD

**Issue by Ujeeee** [coopiteasy/vertical-cooperative#313]
I cannot install Easy My Coop module, because I was missing the "partner_contact_birthdate" module, but I cannot find it anywhere, in this repository or in the addons repository

**Comment by robinkeunen** [comment]
Hi there,

`partner_contact_birthdate` is in [oca/partner-contact](https://github.com/oca/partner-contact). You can find all the repositories we depend on here: https://github.com/coopiteasy/vertical-cooperative/blob/12.0/oca_dependencies.txt

**Comment by Ujeeee** [comment]
thanks for your reply, I will look for this ASAP
