### ISSUE TITLE
Bug with cooperator_type

### ISSUE THREAD

**Issue by victor-champonnois** [coopiteasy/vertical-cooperative#318]
Bug (found on urbike test) that happens when two shares have the same default_code. If a partner become cooperator with one of the share with the default_code equals to another share, the cooperator_type is not correct. 
Bug found by @polchampion

**Comment by enricostano** [comment]
I guess that this could be related to https://github.com/coopiteasy/vertical-cooperative/issues/345

**Comment by victor-champonnois** [comment]
closing in favor of https://github.com/OCA/cooperative/issues/18
