### ISSUE TITLE
Prevent blank share short_name in the form

### ISSUE THREAD

**Issue by victor-champonnois** [coopiteasy/vertical-cooperative#319]
The front-end form uses the short name of the share. If the short name is left empty, the name of the share in the form is therefore blank.
Two potential fixes:
- use full name instead of short name
- use full name if short name is empty

**Comment by victor-champonnois** [comment]
@robinkeunen What do you think about:

>use full name instead of short name

Tested and it seems to be OK regarding the form layout (enough space in the field for a reasonably long name).

Computer layout

![image](https://user-images.githubusercontent.com/92781722/192239647-b0e5f547-7ab0-4272-8272-ba5140f254cd.png)

Mobile layout

![image](https://user-images.githubusercontent.com/92781722/192239506-52149b15-0656-4953-ad5e-0f373eb552b2.png)

**Comment by robinkeunen** [comment]
I think it's a good idea and @enricostano seems to agree with this. I'd ask the functional team though, they know better.

**Comment by victor-champonnois** [comment]
closed in favor of https://github.com/OCA/cooperative/issues/23
