### ISSUE TITLE
Docker compose deployment

### ISSUE THREAD

**Issue by Ujeeee** [coopiteasy/vertical-cooperative#335]
Dear developers, can you make docker compose version so it is easy to deploy in docker environment. Maybe with just docker-compose up and the system is ready with all addons ready to install.

**Comment by robinkeunen** [comment]
Hi Ujeeee, we have no Docker skills at Coop IT Easy to do that, maybe @enricostano ? Anyway, you're welcome to submit a PR. :-)

Do you intend to use those modules yourself ? Welcome !

**Comment by enricostano** [comment]
Hi @Ujeeee !
This repository contains only Odoo modules, it's not a stand-alone application. You need to install Odoo community edition (with [docker](https://github.com/Tecnativa/doodba) if you want) and install the modules offered by this repository.

**Comment by Ujeeee** [comment]
I have odoo 14 running in docker. I see you guys are making the migration
to version 14. Maybe I will wait until some module is ready for odoo 14.

**Comment by robinkeunen** [comment]
Yes, coming soon indeed :-)

**Comment by Ujeeee** [comment]
Great, thanks!

**Comment by robinkeunen** [comment]
@Ujeeee did you see the modules are ready in v14 ? :-)

**Comment by Ujeeee** [comment]
not yet, I will check it soon. Thank you
