### ISSUE TITLE
Permission error validating a draft request

### ISSUE THREAD

**Issue by victor-champonnois** [coopiteasy/vertical-cooperative#340]
Error happened when testing beesdoo_base but was also found in a DB with cooperator and without beesdoo_base. 
https://github.com/beescoop/Obeesdoo/pull/384

- Testing beesdoo_base split on lenid.test.coopiteasy.
- Creation of a user who has only the right to use cooperative management and accounting (
- login with this user
- go to cooperators menu and validate a draft request (to male the whole process of creating a new coop and his eaters). I've - got this error message:" Désolé, vous n’êtes pas autorisé à modifier ce document. Seuls les utilisateurs avec les niveaux d'accès suivants sont actuellement autorisés à faire cela: - Administration/Access Rights"
-  to go on with the test, I add this user rights to my user
- I retry, this error occurs:  
"Désolé, vous n'êtes pas autorisé à créer ce type de document. Seuls les utilisateurs avec les niveaux d'accès suivants sont actuellement autorisés à faire cela: - Other Extra Rights/Accounting / Payments

**Comment by robinkeunen** [comment]
cf https://github.com/beescoop/Obeesdoo/pull/427

**Comment by victor-champonnois** [comment]
closed in favor of https://github.com/OCA/cooperative/issues/19
