### ISSUE TITLE
Reason for get company from 2 different sources in function WebsiteSubscription.fill_values()

### ISSUE THREAD

**Issue by XavierBonetViura** [coopiteasy/vertical-cooperative#341]
Hi!

In [SomEnergia](https://github.com/Som-Energia) we are collaborating with [CoopDevs](https://github.com/coopdevs) in a project [Singulars](https://blog.somenergia.coop/etiqueta/projecte-singulars/) that require to implement 'multicompany' capability to some of the set of Easy-my-coop (vertical-cooperative) modules.

On this process we detect that inside this module: https://github.com/coopiteasy/vertical-cooperative/blob/12.0/cooperator_website/controllers/main.py

... there is a function `def fill_values(self, values, is_company, logged, load_from_user=False):` that is doing 2 different calls to get the company:
- https://github.com/coopiteasy/vertical-cooperative/blob/35443a5179fff137b1f7e69a09cc7b9b17412343/cooperator_website/controllers/main.py#L171
- https://github.com/coopiteasy/vertical-cooperative/blob/35443a5179fff137b1f7e69a09cc7b9b17412343/cooperator_website/controllers/main.py#L209

The question is why is needed to do 2 different calls and use 2 different variables that references the company instead use only one of them inside this function (for example use only 'company' instead 'comp' from line 209 to the end)

**Comment by enricostano** [comment]
@robinkeunen what do you think? Thanks!

**Comment by robinkeunen** [comment]
Hi @XavierBonetViura and thanks for contributing. I don't see a good reason for using these different calls. Moreover, `def _company_default_get` is marked as deprecated in the code. So please go ahead and make the change 👍 

Note that as of version 13.0, the good way to fetch the company will be `env.company`.

**Comment by XavierBonetViura** [comment]
Hi @robinkeunen. Ok, thanks for your reply.

**Comment by robinkeunen** [comment]
cf https://github.com/coopiteasy/vertical-cooperative/pull/342/commits/f419d6e022812e4458de0d40c37457d13f6b7258
