### ISSUE TITLE
12.0 move send_mail_with_multiple_attachments in separate module

### ISSUE THREAD

**Issue by victor-champonnois** [coopiteasy/vertical-cooperative#348]
- the method `send_mail_with_multiple_attachments` from l10n_be_cooperator should be put in a separate modules in addons.
- it could be proposed to the OCA.

We could also use [this module](https://github.com/OCA/social/tree/13.0/mail_template_multi_attachment), after backporting it to 12 or forward porting it to 14.

**Comment by robinkeunen** [comment]
Definitely replace by OCA's module

**Comment by victor-champonnois** [comment]
closed in favor of https://github.com/OCA/cooperative/issues/17
