### ISSUE TITLE
14to12: remove old_member from cooperator_list 

### ISSUE THREAD

**Issue by victor-champonnois** [coopiteasy/vertical-cooperative#351]
Remove `old_member` from the [domain](https://github.com/coopiteasy/vertical-cooperative/blob/35443a5179fff137b1f7e69a09cc7b9b17412343/cooperator/views/res_partner_view.xml#L195) in the cooperator contact tree/kanban list. 

Done in v14, could be done in v12
task : https://gestion.coopiteasy.be/web#id=8962&action=475&active_id=260&model=project.task&view_type=form&menu_id=536

**Comment by victor-champonnois** [comment]
changes in v14 are in [this PR](https://github.com/coopiteasy/vertical-cooperative/pull/339)

**Comment by polchampion** [comment]
@victor-champonnois Not sure what should be tested, but the default filter "Anciens Coopérateurs" still exists in the Cooperators menu.

 
![screenshot-spp test coopiteasy be-2022 09 08-14_12_37](https://user-images.githubusercontent.com/92738727/189119032-f158456c-7681-47b0-9bcf-5202444972fd.png)

**Comment by victor-champonnois** [comment]
@polchampion What should be tested is that old cooperators do not appear in Cooperators bydefault. The task is not about the filter.

**Comment by polchampion** [comment]
@victor-champonnois Sucessfully tested

**Comment by victor-champonnois** [comment]
fixed by https://github.com/coopiteasy/vertical-cooperative/pull/372
