### ISSUE TITLE
14to12: Improve translations 

### ISSUE THREAD

**Issue by victor-champonnois** [coopiteasy/vertical-cooperative#353]
- remove fr_be translation (it is the same as the fr translation, plus translations works additively, we can put only BE specific changes in fr_be, we don't need to maintain a parallel .po file)
- translate mail_templates

Done in v14 (for french), could be done in v12
task : https://gestion.coopiteasy.be/web#id=8962&action=475&active_id=260&model=project.task&view_type=form&menu_id=536

**Comment by victor-champonnois** [comment]
changes in v14 are in [this PR](https://github.com/coopiteasy/vertical-cooperative/pull/339)

**Comment by robinkeunen** [comment]
cf pr

**Comment by polchampion** [comment]
Pas testé car pas sûr quoi regarder
