### ISSUE TITLE
14to12 : remove update cooperator info button

### ISSUE THREAD

**Issue by victor-champonnois** [coopiteasy/vertical-cooperative#355]
The button is not useful. It updates the contact based on the subscription request info. The wizard seems to be never used and it is not well designed (the interface is misleading). If there are missing data in the contact that are in the sub request, it is the write method of contact that should be improved. 

see this [task](https://gestion.coopiteasy.be/web#id=8923&action=475&active_id=260&model=project.task&view_type=form&menu_id=536)

**Comment by victor-champonnois** [comment]
changes in v14 are in [this PR](https://github.com/coopiteasy/vertical-cooperative/pull/339)

**Comment by polchampion** [comment]
LGTM
