### ISSUE TITLE
Improve Readme

### ISSUE THREAD

**Issue by sseerrggii** [coopiteasy/vertical-cooperative#38]
Hi! In @coopdevs we will test vertical-cooperative with Odoo v12

After that I would like to improve Readme file

Do you have some functional documentation?

**Comment by houssine78** [comment]
@sseerrggii sorry I just see your message now. Next time just tag me on the issue like this I'll receive a notification on my mail.

My colleague Catherine is working on a documentation. I'll ask here what she had so far. She's part time and will come back tuesday. I'll come back to you with an answer.

**Comment by sseerrggii** [comment]
Yes, will be great if we can create collaborative documentation :boom: 

Maybe here https://github.com/coopiteasy/vertical-cooperative/wiki we can create a English version

**Comment by houssine78** [comment]
Hi @sseerrggii, Catherine told me that she's still working on the documentation. She think she'll finish the doc this week, it will be in french so far. We have maybe a partner in Germany that is eager to make the translation to english as we're lacking time.

But as Catherine is not tech and has no account in github she prefer to share the document through google drive. I know Google is the devil :) Ok from your side to contribute on a google document ?

**Comment by sseerrggii** [comment]
Yes! I love to work with evil

You can invite me with sseerrggii at gmail

**Comment by sseerrggii** [comment]
Hi @houssine78 ! I see you close this.

My idea was to do this task (improve Readme.md) when I test the modules a bit. I will make a Pull Request that will close the issue. Having issues can help us to manage the pending tasks. Don't you think?

**Comment by houssine78** [comment]
Hi @sseerrggii 

Yes sorry I though that receiving link to the google doc was putting this task obsolete. Sorry I reopen the issue.

**Comment by robinkeunen** [comment]
@sseerrggii @houssine78 Now that the documentation website is under way, can we close this issue?

**Comment by sseerrggii** [comment]
Yes @robinkeunen ! Also the github project have a good readme now! :heart:
