### ISSUE TITLE
Remove `sale` from cooperator dependencies?

### ISSUE THREAD

**Issue by victor-champonnois** [coopiteasy/vertical-cooperative#385]
`sale` does not seem to be needed for the `cooperator` module. I think we can remove it.

Preliminary tests:
- [x] Removing sale from the dependencies and then installing cooperator doesn't raise any error or warning.
- [x] Testing simple flows works OK
- [x] I did a quick search in the code for stuff that would "seem" to depend on sale but did not find anything. 

some observations:
- `product` is needed but it is already a dependency. 
- account journals of type `sale` are defined in `account`, not in `sale`

**Comment by robinkeunen** [comment]
- [ ] Check that sale remains installed when removed from dependencies.

**Comment by victor-champonnois** [comment]
closed in favor of https://github.com/OCA/cooperative/issues/16
