### ISSUE TITLE
cooperator: rename old_member to former_member

### ISSUE THREAD

**Issue by victor-champonnois** [coopiteasy/vertical-cooperative#386]
former_member seems like a more proper way to define a partner who is no longer member. 
- Low priority
- Related to the discussion in this PR https://github.com/coopiteasy/vertical-cooperative/pull/372

**Comment by huguesdk** [comment]
and also harmonize field description strings for `member` and `old_member` (and their translations) between “effective member” or “effective cooperator”. see also [robinkeunen’s remark here](https://github.com/coopiteasy/vertical-cooperative/pull/372#discussion_r977391701).

**Comment by victor-champonnois** [comment]
closed in favor of https://github.com/OCA/cooperative/issues/15
