### ISSUE TITLE
remove duplication from email templates

### ISSUE THREAD

**Issue by huguesdk** [coopiteasy/vertical-cooperative#389]
currently, email templates contain a lot of duplication:

*   the main formatting markup (`div` with styling in which the whole content is wrapped)
*   the greetings (“Hello `${firstname}`,”)
*   the signature and the company information

there are currently 8 email templates, and this content is duplicated across them. this makes updating any of those parts difficult, and also makes translations difficult, as the whole content is translated as one string.

i think that it would be better to have the duplicated content moved to separate templates that would be combined together with the content.

**Comment by victor-champonnois** [comment]
closed in favor of https://github.com/OCA/cooperative/issues/14
