### ISSUE TITLE
RFC - API Easy My Coop - Investor Wallet Platform

### ISSUE THREAD

**Issue by robinkeunen** [coopiteasy/vertical-cooperative#63]
# RFC API Easy My Coop - Investor Wallet Platform

RFC: Request For Comments.

## Context

Coop IT Easy is part of the project _Synergie_ that aims to build a platform for cooperative and citizens. The goal of the platform is  to

- allow citizens to take shares in the participating cooperatives,
- allow cooperatives to manage subscription request from the platform.

The platform code is on GitHub: [investor-wallet-platform](https://github.com/coopiteasy/investor-wallet-platform). It is essentially an extension of Easy My Coop and *depends* on easy my coop.\* 

## Goal

Some cooperatives on the platform already have a tool to manage their subscription. One of these tool is Easy My Coop. The goal of opening an API (on the platform and on Easy My Coop) is 

1. to allow external tool to get subscription requests into their tools
2. Specifically, to allow easy my coop user to manage the subscription from easy my coop and not from the platform.

We're targeting version 12 and up only.

[Easy My Coop documentation](https://docs.google.com/document/d/1sbnoLJOOxBV98x-KTxYqICvZ6gJiLaIncp2riOgfskQ/edit#heading=h.tb6ibqbmam3j)

## Design questions

- Who is pushing / pulling data?
  - I'm leaning towards an API on the platform side
  - EMC will be the source of the actions and maintain mapping between records
  - maybe use https://odoo-connector.com/guides/concepts.html -> mappings
- Odoo [xml-rpc](https://www.odoo.com/documentation/12.0/webservices/odoo.html) or [rest-framework](https://github.com/OCA/rest-framework)?
	- Leaning towards REST
		- Cleaner contracts
		- Easier for non-odoo applications
		- less "out of the box"
		- XXI's century
- On which key are record synchronised?
- swagger and GraphQL?
- Authentification

## Taking a share: flow

The flow to take a share is the following

1. Submitting a subscription request (SR)
2. Validating a SR
	- For a new cooperator
	- For an existing cooperator (capital increase)
3. Record payment
	- creates a share line.

But also, not covered in the first iteration,

- Cancelling a SR
- The cooperator has paid too much or not enough
- Selling back shares
- Subscription register
- Loan management

## Needs - Platform side

Each cooperative only has access to its own data.
Data is transmitted in json format.

1. Get SR list
	- GET 
	- id, name, request date, share, partner, quantity, state
	- filter by date range
	- filter by state (?)
2. Get SR data by id 
	- GET
	- all fields?
3. Validate a request
	- POST
4. Record payment for a capital release
	- POST
	- by id (for request? or invoice? Both?)
	- amount, journal, payment date, memo
	- only full payment for a start?
5. Get cooperator list
	- GET
6. Get cooperator data
	- GET

## Needs - Easy My Coop side

1. Regularly fetch new SR submitted on the platform
2. Fetch new cooperators
2. Post SR validation
3. Post received payment
4. Maintain mapping between records from the platform and Easy My Coop
	- in a table (model, id_iwp, id_emc) + Many2One on records
	- in a field `iwp_key` on the records

For the try: POST a subscription request on EMC

## About Open Sourcing Easy My Coop

EMC was under the AGPL from the start but nothing was made to create a community over the software. 

Developing the API will be the opportunity to

- embark other cooperatives in the adventure (Coopdev, Som Mobilidad, GRAP, ...)
- provide resources necessary for effective contribution (readme, how tos, doc, ...)
- Refactor codebase for maintainability
- Comply with OCA standards.

## Attestation

l’utilisateur de la plateforme doit pouvoir télécharger ses attestations. La question est de savoir si

 1. l’attestation est générée sur la plateforme, téléchargée par l’investisseur,
 2. l’attestation est générée sur l'app de l’entreprise, renvoyée à la plateforme, téléchargée par l’investisseur.

## Additional notes

\* Some parts of easy my coop have been twisted to make synergie possible, fast. We (Robin) are eager to refactor into a cleaner architecture.

**Comment by remytms** [comment]
Thanks for this work.

I will not split needs between platform and emc as the platform is mainly emc with some more features but rather splitting between emc and the connector. So that, all your needs about the platform should be needs for EMC. And all your needs for EMC should be needs of the connector. So just naming convention, seams more clear for me.

Should we also manage Operation Request ?

On the "Platform needs":
I think we should begin simple. The GET list should return all the SR with all the fields without filter. Filters should happen only when explicitly specified by the caller. And the GET SR by id should return all fields.

For the rest of your question, I've not clear opinion for now.

**Comment by robinkeunen** [comment]
@remytms Thank you for the comments. I am splitting platform and emc needs because we will have to install it on both instances, that is EMC instances will talk to the platform without having IWP installed.

Or aye you saying the API points on the platform side won't need any iwp specifics? Let's talk about it _tantôt_.

**Comment by robinkeunen** [comment]
After a talk with Rémy, I'm leaning towards coding most of the API on easy_my_coop side and add specific modules to iwp (the platform) to manage multiple structures. The ir.rules might give us that for free.

**Comment by houssine78** [comment]
@robinkeunen for me if you use the login and password of the structure to connect easy my coop instance to the plateform. You will need to have something on iwp to by pass/delegate the workflow to the stand alone easy my coop of the structure.

Not sure that we can afford a big refactoring from a budget and timing point of view. But it can be discussed of course.
