### ISSUE TITLE
Easy My Coop application icon

### ISSUE THREAD

**Issue by enricostano** [coopiteasy/vertical-cooperative#70]
Hi,
I've noticed that there is no application icon for EMC, in the application launcher the EMC icon is left blank.
I was looking for something like `easy_my_coop/static/description/icon.svg` but I could not find anything.

How do you manage this in your current installations? Thanks!

Screenshot :point_down: 

![image](https://user-images.githubusercontent.com/748971/75701162-919b5900-5cb3-11ea-92a7-47367a128c05.png)

**Comment by robinkeunen** [comment]
Hi @enricostano, don't forget to tag people: we don't get notifications on issues. :-)

The short answer is: we never thought about it, we navigate to the app through the menu bar. Happy to add an icon if you have one in mind.

**Comment by sseerrggii** [comment]
Hey! I made a quick icon, what do you think? 
As long as we don't have someone who can work these kind of things IMO better something than nothing :)

![Screenshot_2020-03-26 Bústia d'entrada - Odoo(1)](https://user-images.githubusercontent.com/2297137/77662144-c9788200-6f7b-11ea-8066-86847a89c4ef.png)

![icon](https://user-images.githubusercontent.com/2297137/77662121-c1b8dd80-6f7b-11ea-918f-2749e43c9a6f.png)

[SVG](https://trello-attachments.s3.amazonaws.com/52383955a37d60d917002557/5e7cc2a0c765c477ead40499/acdc99fc6d719b4be7f995d2f417481f/icon.svg)

**Comment by robinkeunen** [comment]
Hi @sseerrggii , I don't see the link between leaves and cooperatives but yes, it's better than nothing :-) Can you make a PR for it?

Thank you!

**Comment by sseerrggii** [comment]
Hi @robinkeunen 

Why leaf? I was thinking on: 
* Food coops
* Organic kind of economy, like nature :four_leaf_clover: 

About PR, I will need help to know witch files edit, maybe @enricostano can help me with that :wink:

**Comment by robinkeunen** [comment]
Haha ok, let's go for the leaf :-)

**Comment by houssine78** [comment]
a leaf of canabis ?

**Comment by robinkeunen** [comment]
I'm working on a big PR to integrate OCA conventions to 12.0: https://github.com/coopiteasy/vertical-cooperative/pull/84

@sseerrggii can you make a PR on that branch to add the leaf?

**Comment by sseerrggii** [comment]
About PR, I will need help to know witch files edit, @enricostano will help me with that

**Comment by enricostano** [comment]
Yep, will do ASAP.

**Comment by houssine78** [comment]
PR merged, I close the issue then.
