### ISSUE TITLE
[12.0] Is share default_code attribute mandatory?

### ISSUE THREAD

**Issue by enricostano** [coopiteasy/vertical-cooperative#90]
Using EMC demo data and going to cooperators list view, the `cooperator_type` field always shows the first share type.

![image](https://user-images.githubusercontent.com/748971/80471761-26cd6d80-8944-11ea-9674-094068a836ae.png)

Cooperator Manuel Dublues actually has "Part B" share, but in the cooperator list view it shows "Part A".

Digging into the code I found that https://github.com/coopiteasy/vertical-cooperative/blob/12.0/easy_my_coop/models/partner.py#L91 relies on `share_product_id.default_code`. Is it mandatory?

I also tried to set share `default_code` but the cooperator list views showed an empty `cooperator_type` column instead.

Any hint? Thanks!

**Comment by enricostano** [comment]
@houssine78 @robinkeunen @mclaeysb whenever you have some time to give a look at this issue. Thanks!

**Comment by houssine78** [comment]
Hi @enricostano Yes this field is mandatory when is_share is checked. Is made from the view side as we don't want to force it for every product.

Here is the place where we made it required conditionnaly 
https://github.com/coopiteasy/vertical-cooperative/blob/12.0/easy_my_coop/views/product_view.xml#L58

I hope it helps

**Comment by enricostano** [comment]
@houssine78 ok, so we should add this in our demo data https://github.com/coopiteasy/vertical-cooperative/blob/12.0/easy_my_coop/demo/coop.xml#L83

Right?

In any case, I will investigate a bit more since adding a `default_code` to the shares doesn't solve the issue. I'll report back ASAP. Thanks!

**Comment by houssine78** [comment]
@enricostano yes you should add it there. I see that the subscription register is not filled in the demo data if you added demo data for share line you should add the corresponding line in the subscription register.

normally modifying the default code on the share should trigger a recomputation of the cooperator type according to this line https://github.com/coopiteasy/vertical-cooperative/blob/12.0/easy_my_coop/models/partner.py#L84

If you encore that on a demo database a quicker solution should to add the default_code to the demo data and create a new demo db from scratch and see if it works.

**Comment by robinkeunen** [comment]
@enricostano @houssine78 can we close this issue?

**Comment by enricostano** [comment]
Yes, thanks!

cc/ @danypr92 @cesarlr
